version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: mikro-postgres
    environment:
      POSTGRES_USER: mikro
      POSTGRES_PASSWORD: mikro
      POSTGRES_DB: mikro_test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mikro"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
